const hamsters = [
  { id: 1, name: "Boba", age: "6 months", personality: "Gluttonous 🍽️", favouriteFood: "Sunflower Seeds", hobby: "Running on the wheel", bio: "Boba has loved food since birth. His cheeks are legendary — they once held 47 sunflower seeds at once.", image: "/hamsters/Boba.jpg", feed: ["Just ate 12 sunflower seeds in one sitting. New record!! 🏆", "The wheel got an upgrade today. Gotta go fast!! 💨", "Someone dropped a crumb near my cage. Best day ever."], catchphrase: "MORE! Give me MORE!! 🤩" },
  { id: 2, name: "Mochi", age: "4 months", personality: "Shy 😳", favouriteFood: "Strawberries", hobby: "Burrowing in bedding", bio: "Mochi is a gentle soul who prefers the cozy darkness of her blanket nest. Strawberries are the key to her heart.", image: "/hamsters/Mochi.jpg", feed: ["Built a new tunnel today. It's very cozy in here. 🏠", "Someone left a strawberry outside my hideout... tempting... 🍓", "I think I'm starting to like this place. Don't tell anyone."], catchphrase: "...is it safe? ...thank you... 🥺" },
  { id: 3, name: "Tofu", age: "5 months", personality: "Energetic ⚡", favouriteFood: "Broccoli", hobby: "Climbing everything", bio: "Tofu never stops moving. Cages? Climbed. Wheels? Sprinted. Your heart? Stolen.", image: "/hamsters/Tofu.jpg", feed: ["Climbed to the TOP of the water bottle today!! 🧗", "Broccoli for breakfast, broccoli for lunch, broccoli for LIFE!! 🥦", "Did 500 wheel spins before noon. What's YOUR record?? ⚡"], catchphrase: "WHEEEE! Best day ever!! 🎉" },
  { id: 4, name: "Pudding", age: "7 months", personality: "Shy 😳", favouriteFood: "Carrots", hobby: "Hiding in tunnels", bio: "Pudding is a master of hide and seek — mostly hide. She only comes out when she hears the crinkle of a carrot bag.", image: "/hamsters/Pudding.jpg", feed: ["Dug a new emergency escape tunnel. Just in case. 🕳️", "I heard a noise. I'm staying in here for a bit. 🙈", "The carrots were really good today. Worth coming out for."], catchphrase: "...do you have treats? 🥺" },
  { id: 5, name: "Sesame", age: "8 months", personality: "Gluttonous 🍽️", favouriteFood: "Apples", hobby: "Hoarding food in cheeks", bio: "Sesame is a professional food hoarder. Apples are his currency, and he's a billionaire.", image: "/hamsters/Sesame.jpg", feed: ["Cheek capacity update: currently holding 5 treats. Room for more. 🌰", "Found a forgotten snack in my stash. Jackpot!! 🎰", "Apples are objectively the best food. I will not debate this."], catchphrase: "My cheeks are UNLIMITED!! 🤩" },
  { id: 6, name: "Dumpling", age: "9 months", personality: "Chill 😌", favouriteFood: "Sweet Corn", hobby: "Taking dust baths", bio: "Dumpling is the zen master of the hamster world. Nothing fazes her.", image: "/hamsters/Dumpling.jpg", feed: ["Took a long dust bath today. Feeling refreshed. 🧘", "Sweet corn for dinner. Simple pleasures. 🌽", "The sun hit my cage at a perfect angle. Good day."], catchphrase: "Life is good when you're round. 🧘" },
  { id: 7, name: "Peanut", age: "5 months", personality: "Chaotic 💫", favouriteFood: "Peanuts", hobby: "Escaping the cage", bio: "Peanut is an escape artist. Three cages, seven attempted breakouts, two successful ones.", image: "/hamsters/Peanut.jpg", feed: ["Almost escaped again today. I'll get it tomorrow. 🏃💨", "The new cage lock looks tougher... challenge accepted!! 🔓", "PEANUTS!! My favorite!! Freedom can wait!! 🥜"], catchphrase: "NYOOOM!! 💨" },
  { id: 8, name: "Cookie", age: "10 months", personality: "Picky 🤔", favouriteFood: "Blueberries", hobby: "Napping in cozy spots", bio: "Cookie has standards. High ones. She only eats the finest blueberries.", image: "/hamsters/Cookie.jpg", feed: ["The bedding was re-fluffed today. Acceptable. 😌", "These blueberries are adequate. Barely. 🫐", "I require exactly 4 more hours of sleep. Do not disturb."], catchphrase: "Hmm... acceptable. Barely. 🤔" },
  { id: 9, name: "Maple", age: "11 months", personality: "Picky 🤔", favouriteFood: "Sweet Potato", hobby: "Rearranging the cage", bio: "Maple is an interior designer trapped in a hamster's body. She knows what she likes.", image: "/hamsters/Maple.jpg", feed: ["Redecorated the entire east wing of the cage today. 🏗️", "The sweet potato pairing with this corner is immaculate. 🍠", "Who put the water bottle THERE?? I'm fixing it immediately."], catchphrase: "This corner is all wrong! 🍁" },
  { id: 10, name: "Churro", age: "3 months", personality: "Chaotic 💫", favouriteFood: "Cinnamon Oats", hobby: "Sprinting at 3am", bio: "Churro is why you hear running wheel noises at 3am. He has NO off switch.", image: "/hamsters/Churro.jpg", feed: ["3AM AND I'M STILL ON THE WHEEL!! WHO NEEDS SLEEP?? 🌙", "Cinnamon oats for DINNER!! This is NOT a drill!! 🥣", "I broke my speed record AGAIN. The wheel is SMOKING. 💫"], catchphrase: "THE SUSPENSE IS KILLING MEEEEE!! 💀💫" },
  { id: 11, name: "Snowball", age: "7 months", personality: "Chill 😌", favouriteFood: "Cucumber", hobby: "Grooming fur", bio: "Snowball is elegance in hamster form. Her white fur is always immaculate.", image: "/hamsters/Snowball.jpg", feed: ["Spent 3 hours grooming today. My fur is GLOWING. ❄️", "Cucumber was served at the perfect temperature. Finally. 🥒", "A lady must maintain her standards. Always. 🎀"], catchphrase: "Looking this fluffy takes work. ❄️" },
  { id: 12, name: "Biscuit", age: "6 months", personality: "Friendly 🥰", favouriteFood: "Banana Chips", hobby: "Digging endless tunnels", bio: "Biscuit is everyone's best friend. She greets every visitor with a happy squeak.", image: "/hamsters/Biscuit.jpg", feed: ["I dug a new tunnel!! It leads to... more tunnel!! 🐹💛", "Banana chips today!! Sharing with EVERYONE!! 🍌", "Made a new friend today. (It was my reflection. Still counts.)"], catchphrase: "You're my BEST FRIEND!! 💕" },
];

export default hamsters;
